function apply_clean_plot_style(ax)
%APPLY_CLEAN_PLOT_STYLE Standardize figure styling for saved plots.

if nargin < 1 || isempty(ax) || ~isgraphics(ax, 'axes')
    ax = gca;
end

fig = ancestor(ax, 'figure');
if ~isempty(fig) && isgraphics(fig, 'figure')
    set(fig, 'Color', 'w');
end

set(ax, ...
    'Color', 'w', ...
    'Box', 'on', ...
    'Layer', 'top', ...
    'LineWidth', 1, ...
    'FontName', 'Arial', ...
    'FontSize', 11, ...
    'GridAlpha', 0.18, ...
    'MinorGridAlpha', 0.10, ...
    'XGrid', 'on', ...
    'YGrid', 'on', ...
    'XMinorGrid', 'on', ...
    'YMinorGrid', 'on');

try
    colororder(ax, [
        0.0000 0.4470 0.7410; ...
        0.8500 0.3250 0.0980; ...
        0.9290 0.6940 0.1250; ...
        0.4940 0.1840 0.5560; ...
        0.4660 0.6740 0.1880; ...
        0.3010 0.7450 0.9330]);
catch
end

if ~isempty(fig) && isgraphics(fig, 'figure')
    leg = findall(fig, 'Type', 'Legend');
    for k = 1:numel(leg)
        try
            set(leg(k), 'FontName', 'Arial', 'FontSize', 10, 'Box', 'off');
        catch
        end
    end
end
end